### ISSUE TITLE
Why p2 do not have "hard_targets"?

### ISSUE THREAD

**Issue by yumath** [BillAmihom/RAPQ#2]
Thank for your implementation, but I have a question below:
Why p2 do not have "hard_targets"? line:54 in else branch, p2 also get soft target
https://github.com/BillAmihom/RAPQ/blob/aaa71dff8e8e3e871be314610ae9e6861593a0a3/quant/adaptive_rounding.py#L50-L54

**Comment by BillAmihom** [comment]
hi longyu. line58 to line65 do the equal thing with “hard_targets”. It's better than get hard_targets by round( soft_targets).

**Comment by yumath** [comment]
@BillAmihom Thx very much!
